<a href="https://colab.research.google.com/github/ikhsan0725/nbc/blob/main/nbc_hilda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Menentukan data x dan y

In [3]:
dataset = pd.read_csv("try.csv")
x = dataset.iloc[:, [1,2,3,]].values
y = dataset.iloc[:, -1].values

lihat data x

In [4]:
print (x)

[[2 2 4]
 [1 4 2]
 [3 3 3]
 [3 4 3]
 [4 3 5]
 [4 4 5]
 [2 4 2]]


lihat data y

In [5]:
print (y)

[0 0 1 1 1 1 0]


Pisahkan data training dengan testing

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.28571428571, random_state=0)

Munculkan data x, y train dan test

In [7]:
print (x_train)

[[1 4 2]
 [3 4 3]
 [2 2 4]
 [4 4 5]
 [4 3 5]]


In [8]:
print(x_test)

[[2 4 2]
 [3 3 3]]


In [9]:
print (y_train)

[0 1 0 1 1]


In [10]:
print (y_test)

[0 1]


Membuat skala standar x

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

Cek hasil

In [12]:
print (x_train)

[[-1.54348727  0.75       -1.54348727]
 [ 0.17149859  0.75       -0.68599434]
 [-0.68599434 -1.75        0.17149859]
 [ 1.02899151  0.75        1.02899151]
 [ 1.02899151 -0.5         1.02899151]]


In [13]:
print (x_test)

[[-0.68599434  0.75       -1.54348727]
 [ 0.17149859 -0.5        -0.68599434]]


Panggil NBC

In [14]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train, y_train)

GaussianNB()

Hitung prediksi

In [15]:
y_pred = classifier.predict(x_test)

Hitung evaluasi keakuratan prediksi

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
am = accuracy_score(y_test, y_pred)

Lihat hasil

In [17]:
print(cm)

[[1 0]
 [0 1]]


In [18]:
print(am)

1.0


Diagram penyebaran klasifikasi NBC

In [ ]:

    if not title:
        if normalize:
            title='Normalized Confusion Matrix'
        else:
            title='Confusion Matrix, without normalization'
            
cm = confusion_matrix(y_true, y_pred)

classes = classes[unique_labels(y_true, y_pred)]
if normalize:
    cm = cm.astype('float') / cm.sum(axis=1)[:, np,newaxis]
    print('Normalized Confusion Matrix')
else:
    print('Confusion Matrix, without normalization')
print(cm)

fig, ax = plt.subplots()
im = ax.imshow(cm, interpolation='nearest', cmap=cmap)
ax.figure.colorbar(im, ax=ax)

ax.set(xticks=np.arage(cm.shape[1]),
       yticks=np.arange(cm.shape[0]),
       
       xticklabels=classes, yticklabels=classes,
       title=title,
       ylabel='True label',
       xlabel='Predicted label')
       
plt.setp(ax.get_xticklabels(), rotation=45, ha="right",
       rotation_mode="anchor")

fmt = '.2f' if normalize else 'd'
thresh = cm.max() / 2.
for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):
        ax.text(j, i, format(cm[i, j], fmt),
                ha="center", va="center",
                color="white" if cm[i, j] > thresh else "black")
fig.tight_layout()
return ax

In [ ]:
class_names = y
np.set_printoptions(precision=2)

plot_confusion_matrix(y_test, y_pred, classes=class_names,
                      title='Confusin matrix, withut normalization')

plot_confusion_matrix(y_test, y_pred, classes=class_names, normalize=True,
                      title='Normalized confusion matrix')
plt.show