<a href="https://colab.research.google.com/github/ikhsan0725/nbc/blob/main/nbc_hilda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Menentukan data x dan y

In [7]:
dataset = pd.read_csv("try.csv")
x = dataset.iloc[:, [1,2,3,]].values
y = dataset.iloc[:, -1].values

lihat data x

In [8]:
print (x)

[[2 2 4]
 [1 4 2]
 [3 3 3]
 [3 4 3]
 [4 3 5]
 [4 4 5]
 [2 4 2]]


lihat data y

In [9]:
print (y)

[0 0 1 1 1 1 0]


Pisahkan data training dengan testing

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.28571428571, random_state=0)

Munculkan data x, y train dan test

In [11]:
print (x_train)

[[1 4 2]
 [3 4 3]
 [2 2 4]
 [4 4 5]
 [4 3 5]]


In [12]:
print(x_test)

[[2 4 2]
 [3 3 3]]


In [13]:
print (y_train)

[0 1 0 1 1]


In [14]:
print (y_test)

[0 1]


Membuat skala standar x

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

Cek hasil

In [16]:
print (x_train)

[[-1.54348727  0.75       -1.54348727]
 [ 0.17149859  0.75       -0.68599434]
 [-0.68599434 -1.75        0.17149859]
 [ 1.02899151  0.75        1.02899151]
 [ 1.02899151 -0.5         1.02899151]]


In [17]:
print (x_test)

[[-0.68599434  0.75       -1.54348727]
 [ 0.17149859 -0.5        -0.68599434]]


Panggil NBC

In [18]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train, y_train)

GaussianNB()

Hitung prediksi

In [19]:
y_pred = classifier.predict(x_test)

Hitung evaluasi keakuratan prediksi

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
am = accuracy_score(y_test, y_pred)

Lihat hasil

In [21]:
print(cm)

[[1 0]
 [0 1]]


In [27]:
print(am)

1.0


Diagram penyebaran klasifikasi NBC